/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./lib/**/*.{js,jsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        // shadcn compatibility tokens
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Reference design system — Material You green palette
        "surface-container-lowest": "#151616",
        "inverse-on-surface": "#F4F1EA",
        "on-secondary": "#151616",
        "secondary-fixed": "#242525",
        "on-surface": "#F4F1EA",
        "tertiary-container": "#1E2020",
        "on-secondary-fixed": "#F4F1EA",
        "inverse-surface": "#F4F1EA",
        "primary-fixed-dim": "#9B9992",
        "on-primary-fixed": "#0F1010",
        "error-container": "#4A1515",
        "mn-primary": "#F4F1EA",
        "on-secondary-fixed-variant": "#9B9992",
        "on-primary-fixed-variant": "#D6D2C9",
        "surface-container": "#151616",
        "mn-background": "#0F1010",
        "on-primary": "#0F1010",
        "on-surface-variant": "#9B9992",
        "on-secondary-container": "#9B9992",
        "surface-tint": "#FF5A36",
        "surface-variant": "#1E2020",
        "secondary-container": "#1E2020",
        "tertiary-fixed-dim": "#9B9992",
        outline: "#5D5B56",
        "on-tertiary-fixed": "#0F1010",
        "primary-container": "#1E2020",
        "surface-dim": "#151616",
        "mn-surface": "#0F1010",
        "on-error": "#ffffff",
        "on-background": "#F4F1EA",
        error: "#FF3B30",
        "on-tertiary-container": "#9B9992",
        "on-tertiary": "#ffffff",
        tertiary: "#FF5A36",
        "on-tertiary-fixed-variant": "#5D5B56",
        "tertiary-fixed": "#FF6A3D",
        "secondary-fixed-dim": "#242525",
        "mn-secondary": "#9B9992",
        "on-primary-container": "#FF6A3D",
        "primary-fixed": "#FF6A3D",
        "inverse-primary": "#FF5A36",
        "on-error-container": "#FFDAD6",
        "surface-container-low": "#121313",
        "outline-variant": "#242525",
        "surface-container-high": "#1E2020",
        "surface-container-highest": "#242525",
        "surface-bright": "#0F1010",
        // legacy dark tokens (kept for other pages)
        dark: {
          DEFAULT: "#121212",
          50: "#f9f9f9",
          100: "#e1e1e1",
          200: "#c8c8c8",
          300: "#afafaf",
          400: "#969696",
          500: "#7d7d7d",
          600: "#646464",
          700: "#4b4b4b",
          800: "#333333",
          900: "#1e1e1e",
          950: "#121212",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "2xl": "0.75rem",
        "3xl": "1rem",
        "4xl": "1.25rem",
        "5xl": "1.5rem",
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-lg-mobile": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" },
        ],
      },
      spacing: {
        gutter: "24px",
        "container-padding-desktop": "64px",
        "container-padding-mobile": "24px",
        "section-gap": "120px",
        unit: "8px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-down": {
          "0%": { opacity: "0", transform: "translateY(-20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(20px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        "pulse-subtle": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.8" },
        },
        float: {
          "0%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-15px)" },
          "100%": { transform: "translateY(0px)" },
        },
        "float-reverse": {
          "0%": { transform: "translateY(-15px)" },
          "50%": { transform: "translateY(0px)" },
          "100%": { transform: "translateY(-15px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out",
        "fade-in-up": "fade-in-up 0.6s ease-out",
        "fade-in-down": "fade-in-down 0.6s ease-out",
        "slide-in-right": "slide-in-right 0.6s ease-out",
        "pulse-subtle": "pulse-subtle 2s ease-in-out infinite",
        float: "float 6s ease-in-out infinite",
        "float-reverse": "float-reverse 8s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
